server:
  port: 8080
spring:

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: mysql


  datasource:
    url: jdbc:mysql://localhost:3306/itseoyo?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  file:
    name: ${user.dir}/log/event-check.log
    max-history: 7
    max-size: 10MB
  level:
    org.hibernate.sql: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**